# Generated by Django 4.2.17 on 2025-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lessonTitle',
            field=models.TextField(default='Lesson title', max_length=256),
        ),
    ]
