# Generated by Django 4.2.17 on 2025-03-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning_application', '0002_lesson_lessontitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('contentID', models.AutoField(primary_key=True, serialize=False)),
                ('contentTitle', models.TextField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseContent', to='e_learning_application.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='e_learning_application.teachers')),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mcqquestion',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='McqQuestion',
        ),
    ]
