# Generated by Django 4.2.17 on 2025-03-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning_application', '0003_coursecontent_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdates',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
