# Generated by Django 4.2.17 on 2025-03-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning_application', '0004_statusupdates_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='receiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='e_learning_application.teachers'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='senderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to='e_learning_application.students'),
        ),
    ]
